name: ProcViewSafety

on:
  pull_request:
    branches:
      - main
## this is a test to see if i can push to main (I shouldnt be able to )
jobs:
  test:

    runs-on: windows-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

    
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'  

      
      - name: Install dependencies
        run: go mod tidy


      - name: Run tests
        run: go test -v ./...


  require-tests-passing:
    runs-on: ubuntu-latest
    needs: test
    if: github.event.pull_request.head.ref != 'main'

    steps:
      - name: Check if tests passed
        run: |
          if [ "${{ needs.test.result }}" != "success" ]; then
            echo "Tests did not pass. Merge is not allowed."
            exit 1
          fi
